### PR TITLE
fix: werkzeug 2.1.X support

### PR DESCRIPTION
**Pull request by joranbeasley**
resolves import error and I think it should work 

```
File "E:\flask-project\app.py", line 2, in <module>
    from flask_lambda import FlaskLambda
  File "E:\flask-project\venv\lib\site-packages\flask_lambda.py", line 33, in <module>
    from werkzeug.wrappers import BaseRequest
ImportError: cannot import name 'BaseRequest' from 'werkzeug.wrappers' (E:\flask-project\venv\lib\site-packages\werkzeug\wrappers\__init__.py)
```

### CODE REVIEW

**Review by eduumach — APPROVED** [review]

**Comment by jstarcher** [comment]
Can this get merged? Running into the same issue.

**Comment by anwenyi** [comment]
Please merge this and thanks!

**Comment by Steve-Groner** [comment]
@sivel Can this get merged?

**Review by jfajardo — COMMENTED** [review]
Please merge it

**Review by ranesblueocean — APPROVED** [review]

**Comment by rsnegrin** [comment]
Please merge! Thanks

**Pull request merged**
